# Generated by Django 5.2.8 on 2025-12-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='is_remote_worker',
            field=models.BooleanField(default=False),
        ),
    ]
